spring:
  application:
    name: main-service
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server
    retry:
      useRandomPolicy: true
      max-interval: 6000
